//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetM2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public int IDOBGET { get; set; }
        public string NOM { get; set; }
        public string USERNAME { get; set; }
        public string MDP { get; set; }
        public string LISTLOUEE { get; set; }
        public Nullable<System.DateTime> TIMELOUEE { get; set; }
        public Nullable<System.DateTime> TIMERENDU { get; set; }

        internal object ToList()
        {
            throw new NotImplementedException();
        }
    }
}
