//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetM2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        public int IDOBGET { get; set; }
        public string NAMEFILM { get; set; }
        public string DIRECTOR { get; set; }
        public Nullable<System.DateTime> DATESORTIE { get; set; }
        public string CATEGORIE { get; set; }
        public Nullable<bool> ENSTOCK { get; set; }
        public Nullable<int> LIST { get; set; }
        public Nullable<int> NBPRET { get; set; }
        public string PHOTO { get; set; }
    }
}
